---
lib_name: lib_qadc
project: '{{lib_name}}'
title: '{{lib_name}}: XMOS QADC Library'
version: 1.0.0

documentation:
  exclude_patterns_path: doc/exclude_patterns.inc
  substitutions_path: doc/substitutions.inc
  root_doc: doc/rst/qadc.rst
  linkcheck_ignore_regex: ['']
  cognidox_part_number: XM-015184-UG
  doxygen_projects:
    lib_qadc:
      doxyfile_path: doc/Doxyfile.inc
  pdfs:
    doc/rst/qadc.rst:
      pdf_title: '{{title}}'
      pdf_filename: '{{lib_name}}_v{{version}}'
    README.rst:
      pdf_title: '{{title}} (README)'
      pdf_filename: '{{lib_name}}_v{{version}}_readme'
      pdf_short: yes
software:
  cognidox_part_number: XM-015183-SM
